//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace A7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domitory
    {
        public int Id { get; set; }
        public string 宿舍号 { get; set; }
        public string 人数上限 { get; set; }
        public string 所属院系 { get; set; }
        public Nullable<int> 成员数 { get; set; }
    }
}
